# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    stages: [commit, merge-commit]
  - id: end-of-file-fixer
    stages: [commit, merge-commit]
  - id: check-yaml
    stages: [commit, merge-commit]
  - id: check-added-large-files
    stages: [commit, merge-commit]
- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    language: system
    pass_filenames: false
    types: [terraform]
    stages: [commit, merge-commit]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
        - '@commitlint/config-conventional'
